version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "fear-and-greed-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-4qyi0na7uway"
s3_prefix = "fear-and-greed-app"
region = "eu-north-1"
capabilities = "CAPABILITY_IAM"
image_repositories = ["FearAndGreedFunction=924137863346.dkr.ecr.eu-north-1.amazonaws.com/fear-and-greed-app"]
