AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.8

  SAM template for the RESTful API to access CNN's Fear & Greed Index.

Globals:
  Function:
    Timeout: 3

Resources:
  FearAndGreedFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        GetIndex:
          Type: Api
          Properties:
            Path: /
            Method: get
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./fear_and_greed
      DockerTag: python3.8-v1

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function.
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api.
  FearAndGreedApi:
    Description: "API Gateway endpoint URL for Prod stage for Fear and Greed function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/"
  FearAndGreedFunction:
    Description: "Fear and Greed Lambda Function ARN"
    Value: !GetAtt FearAndGreedFunction.Arn
  FearAndGreedFunctionIamRole:
    Description: "Implicit IAM Role created for Fear and Greed function"
    Value: !GetAtt FearAndGreedFunctionRole.Arn
