name: Deploy github.com/vterron/fear-and-greed to Google App Engine

on: [push]

jobs:
  deploy_job:
    name: Deploy app to Google App Engine
    runs-on: ubuntu-latest
    steps:
      - name: Git repository checkout
        uses: actions/checkout@v2

      - name: Setup Cloud SDK
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GAE_SA_KEY }}
          project_id: ${{ secrets.GAE_PROJECT }}
          export_default_credentials: true

      - name: Deploy to Google App Engine
        run: |-
          # --quiet to skip confirmation prompt.
          gcloud --quiet app deploy
